require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PtReportSchedulesController do

  # This should return the minimal set of attributes required to create a valid
  # PtReportSchedule. As you add validations to PtReportSchedule, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "pt_account" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PtReportSchedulesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET edit" do
    it "assigns the requested pt_report_schedule as @pt_report_schedule" do
      pt_report_schedule = PtReportSchedule.create! valid_attributes
      get :edit, {:id => pt_report_schedule.to_param}, valid_session
      assigns(:pt_report_schedule).should eq(pt_report_schedule)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PtReportSchedule" do
        expect {
          post :create, {:pt_report_schedule => valid_attributes}, valid_session
        }.to change(PtReportSchedule, :count).by(1)
      end

      it "assigns a newly created pt_report_schedule as @pt_report_schedule" do
        post :create, {:pt_report_schedule => valid_attributes}, valid_session
        assigns(:pt_report_schedule).should be_a(PtReportSchedule)
        assigns(:pt_report_schedule).should be_persisted
      end

      it "redirects to the created pt_report_schedule" do
        post :create, {:pt_report_schedule => valid_attributes}, valid_session
        response.should redirect_to(PtReportSchedule.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pt_report_schedule as @pt_report_schedule" do
        # Trigger the behavior that occurs when invalid params are submitted
        PtReportSchedule.any_instance.stub(:save).and_return(false)
        post :create, {:pt_report_schedule => { "pt_account" => "invalid value" }}, valid_session
        assigns(:pt_report_schedule).should be_a_new(PtReportSchedule)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PtReportSchedule.any_instance.stub(:save).and_return(false)
        post :create, {:pt_report_schedule => { "pt_account" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pt_report_schedule" do
        pt_report_schedule = PtReportSchedule.create! valid_attributes
        # Assuming there are no other pt_report_schedules in the database, this
        # specifies that the PtReportSchedule created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PtReportSchedule.any_instance.should_receive(:update_attributes).with({ "pt_account" => "" })
        put :update, {:id => pt_report_schedule.to_param, :pt_report_schedule => { "pt_account" => "" }}, valid_session
      end

      it "assigns the requested pt_report_schedule as @pt_report_schedule" do
        pt_report_schedule = PtReportSchedule.create! valid_attributes
        put :update, {:id => pt_report_schedule.to_param, :pt_report_schedule => valid_attributes}, valid_session
        assigns(:pt_report_schedule).should eq(pt_report_schedule)
      end

      it "redirects to the pt_report_schedule" do
        pt_report_schedule = PtReportSchedule.create! valid_attributes
        put :update, {:id => pt_report_schedule.to_param, :pt_report_schedule => valid_attributes}, valid_session
        response.should redirect_to(pt_report_schedule)
      end
    end

    describe "with invalid params" do
      it "assigns the pt_report_schedule as @pt_report_schedule" do
        pt_report_schedule = PtReportSchedule.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PtReportSchedule.any_instance.stub(:save).and_return(false)
        put :update, {:id => pt_report_schedule.to_param, :pt_report_schedule => { "pt_account" => "invalid value" }}, valid_session
        assigns(:pt_report_schedule).should eq(pt_report_schedule)
      end

      it "re-renders the 'edit' template" do
        pt_report_schedule = PtReportSchedule.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PtReportSchedule.any_instance.stub(:save).and_return(false)
        put :update, {:id => pt_report_schedule.to_param, :pt_report_schedule => { "pt_account" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pt_report_schedule" do
      pt_report_schedule = PtReportSchedule.create! valid_attributes
      expect {
        delete :destroy, {:id => pt_report_schedule.to_param}, valid_session
      }.to change(PtReportSchedule, :count).by(-1)
    end

    it "redirects to the pt_report_schedules list" do
      pt_report_schedule = PtReportSchedule.create! valid_attributes
      delete :destroy, {:id => pt_report_schedule.to_param}, valid_session
      response.should redirect_to(pt_report_schedules_url)
    end
  end

end
